### ISSUE TITLE
IndexError on domain comprehension

### ISSUE THREAD

**Issue by elliott-maguire** [sr-revops/oscr#15]
The following exception is being raised:

    Traceback (most recent call last):
        File "/app/.heroku/python/lib/python3.7/runpy.py", line 193, in _run_module_as_main
            "__main__", mod_spec)
        File "/app/.heroku/python/lib/python3.7/runpy.py", line 85, in _run_code
            exec(code, run_globals)
        File "/app/oscr/__main__.py", line 64, in <module>
            run()
        File "/app/oscr/__main__.py", line 37, in run
            contacts, company_info, summary = enrich(sfc, doc, account)
        File "/app/oscr/utils.py", line 35, in enrich
            re.findall(r"@(\w.+)", c.email)[0] for c in sf_contacts if c.email
        File "/app/oscr/utils.py", line 35, in <listcomp>
            re.findall(r"@(\w.+)", c.email)[0] for c in sf_contacts if c.email
    IndexError: list index out of range

Investigating cause.

**Comment by elliott-maguire** [comment]
Looks like there was a "to-be-deleted" record present from Salesforce that had an email value of "delete".
